In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

results = []

for products_page in range(1, 14):
    url = f"https://www.lookfantastic.com/c/health-beauty/organic-natural/view-all-natural-organic/?facetFilters=en_beauty_formulation_content%3AClean%7CcategoryLevel2%3ASkin+Care&pageNumber={products_page}"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")

    clean_products = soup.find_all("a", class_="product-item")

    for c in clean_products:

        name_product = c.get("data-title")
        link_product = "https://www.lookfantastic.com" + c.get("href")

        product_details = requests.get(link_product)
        detailed_soup = BeautifulSoup(product_details.content, "html.parser")

        try:
            brand_product = detailed_soup.find("a", class_="override-pdp-brand").get_text(strip=True)
        except AttributeError:
            continue

        try:
            ingredients_product = detailed_soup.find("div", attrs={"aria-labelledby": "ingredients"}).find("p").get_text(strip=True)
        except AttributeError:
            continue

        results.append({"Product Name": name_product,
                        "Product Brand": brand_product,
                        "Ingredients": ingredients_product,
                        "Clean Product": True,

        })

df = pd.DataFrame(results)
df.to_csv('clean_skincare_v1.csv', index=False)

df

,Product Name,Product Brand,Ingredients,Clean Product
0,Pai Skincare Rosehip Bioregenerate™ Rejuvenati...,Pai,"Rosa Canina Seed Extract*, Rosa Canina Fruit E...",True
1,Pai Skincare Rosehip Bioregenerate™ Rejuvenati...,Pai,Rosa Canina Seed Extract* (Rosehip Seed Oil Co...,True
2,Elemis Travel Essentials Set,Elemis,Cleansing Balm: Prunus Amygdalus Dulcis (Sweet...,True
3,BEAUTYPRO Eye Therapy Under Eye Mask with Coll...,BEAUTYPRO,"Aqua,Glycerin,Sorbitol,Sodium Polyacrylate,Ric...",True
4,Embryolisse Lait-Crème Concentré Multi-Purpose...,Embryolisse,Aqua. Paraffinum Liquidum. Stearic Acid. Glyce...,True
...,...,...,...,...
388,Burt's Bees Sensitive Daily Moisturising Cream...,Burt's Bees,"Aqua, Helianthus Annuus Seed Oil, Glycerin, Ce...",True
389,Dermalogica Daily Skin Health Trio,Dermalogica,"Cleanser: Water/Aqua/Eau, Disodium Laureth Sul...",True
390,Pai Skincare The Light Fantastic™ Ceramide Fac...,Pai,"Helianthus Annuus Seed Oil* (Sunflower Oil), C...",True
391,PURITO Oat-in Silky Toner 200ml,PURITO,"Avena Sativa (Oat) Seed Water, Butylene Glycol...",True
392,Alpha-H Generation Glow Daily Resurfacing Esse...,Alpha-H,"Aqua (Water), Butylene Glycol, Dodecane, Vacci...",True

In [3]:
pd.set_option('display.max_colwidth', None)

df

,Product Name,Product Brand,Ingredients,Clean Product
0,Pai Skincare Rosehip Bioregenerate™ Rejuvenating Overnight Face Oil 30ml,Pai,"Rosa Canina Seed Extract*, Rosa Canina Fruit Extract*, Tocopherol, Rosmarinus Officinalis Leaf Extract*.",True
1,Pai Skincare Rosehip Bioregenerate™ Rejuvenating Overnight Face Oil,Pai,"Rosa Canina Seed Extract* (Rosehip Seed Oil Co2), Rosa Canina Fruit Extract* (Rosehip Fruit Extract Co2), Tocopherol (Vitamin E), Rosmarinus Officinalis Leaf Extract* (Rosemary Extract), Squalene, Beta-Sitosterol.",True
2,Elemis Travel Essentials Set,Elemis,"Cleansing Balm: Prunus Amygdalus Dulcis (Sweet Almond) Oil, Caprylic/Capric Triglyceride, PEG-6 Caprylic/Capric Glycerides, PEG-8 Beeswax, Cetearyl Alcohol, Sorbitan Stearate, Sambucus Nigra Oil, PEG-60 Almond Glycerides, Fragrance (Parfum), Silica, Avena Sativa (Oat) Kernel Oil, Triticum Vulgare (Wheat) Germ Oil, Butyrospermum Parkii (Shea) Butter, Citrus Aurantium Dulcis (Orange) Peel Wax, Glycerin, Lecithin, Borago Officinalis Seed Oil, Phenoxyethanol, Cocos Nucifera (Coconut) Oil, Acacia Decurrens Flower Wax, Rosa Damascena Flower Wax, Linalool, Tocopherol, Eugenia Caryophyllus (Clove) Leaf Oil, Eugenol, Cocoyl Hydrolyzed Collagen, Limonene, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Pogostemon Cablin Oil, Aqua/Water/Eau, Simmondsia Chinensis (Jojoba) Seed Oil, Coumarin, Cananga Odorata Flower Oil, Cinnamomum Zeylanicum Leaf Oil, Citrus Aurantium Dulcis (Orange) Peel Oil, Citrus Nobilis (Mandarin Orange) Peel Oil, Geraniol, Amyris Balsamifera Bark Oil, Padina Pavonica Thallus Extract, Citral, Benzyl Ben.",True
3,BEAUTYPRO Eye Therapy Under Eye Mask with Collagen and Green Tea Extract (3 Applications),BEAUTYPRO,"Aqua,Glycerin,Sorbitol,Sodium Polyacrylate,Ricinus Communis (Castor) Seed Oil,Polyacrylic Acid,Octyldodecanol,Kaolin,Cellulose Gum,Acacia Concinna Fruit Extract,Camellia Sinensis Leaf Extract,Aloe Barbadensis Leaf Juice Powder,Retinyl Palmitate,Allantoin,Aluminum Hydroxide,Tocopheryl Acetate,Disodium EDTA,Tartaric Acid,Phenoxyethanol,Hydrolyzed Collagen,Butylene Glycol,1,2-Hexanediol,Tocopherol,Citronellol,Limonene,Hydroxycitronellal,Linalool,Parfum,CI77891,CI77288.",True
4,Embryolisse Lait-Crème Concentré Multi-Purpose Moisturiser 75ml,Embryolisse,"Aqua. Paraffinum Liquidum. Stearic Acid. Glyceryl Stearate. Triethanolamine. Cera Alba. Cetyl Palmitate. Butyrospermum Parkii. Steareth-10. Polyacrylamide C13-14 Isoparaffin, Laureth-7. Propylene Glycol, Hydrolyzed Soy Protein, Aloe Barbadensis. 1,2-Hexanediol, Caprylyl Glycol. Tropolone. Parfum.",True
...,...,...,...,...
388,Burt's Bees Sensitive Daily Moisturising Cream 50g,Burt's Bees,"Aqua, Helianthus Annuus Seed Oil, Glycerin, Cetyl Alcohol, Zinc Oxide, Zea Mays Starch, Gossypium Herbaceum Flower Extract, Oryza Sativa Extract, Beta Vulgaris Root Extract, Artemisia Umbelliformis Extract, Euphrasia Officinalis Extract, Butyrospermum Parkii Butter, Saccharum Officinarum Extract, Aloe Barbadensis Leaf Juice, Jojoba Esters, Hydrolyzed Jojoba Esters, Kaolin, Lecithin, Sucrose, Fructose, Glucose, Inositol, Citric Acid, Benzoic Acid, Trehalose, Xanthan Gum, Glyceryl Laurate, Potassium Sorbate, Sucrose Stearate, Sucrose Polystearate, Sodium Benzoate, Sodium Stearoyl Lactylate, Sodium Pca, Alcohol Denat., Phenoxyethanol",True
389,Dermalogica Daily Skin Health Trio,Dermalogica,"Cleanser: Water/Aqua/Eau, Disodium Laureth Sulfosuccinate, Sodium Lauroyl Sarcosinate, Quillaja Saponaria Bark Extract Lavandula Angustifolia (Lavender) Oil, Melissa Officinalis Leaf Extract, Citrus Limon (Lemon) Peel Oil, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Cymbopogon Winterianus Herb Oil, Glycerin, Cocamidopropyl Betaine, Coco-Betaine, Hydroxyethylcellulose, Sodium Cocoyl Isethionate, Capryloyl Glycine, Sodium Lauryl Sulfoacetate, Methylpropanediol, Ethylhexylglycerin, Caprylhydroxamic Acid, PPG-5-Ceteth-20, Sodium Hydroxide, Disodium EDTA.",True
390,Pai Skincare The Light Fantastic™ Ceramide Face Oil 10ml,Pai,"Helianthus Annuus Seed Oil* (Sunflower Oil), Carthamus Tinctorius Seed Oil* (Safflower Oil), Aleurites Moluccanus Seed Oil* (Kukui Oil), Vitis Vinifera Seed Oil* (Grape Seed Oil), Coconut Alkanes, Prunus Domestica Seed Oil* (Plum Oil), Caprylic/Capric Triglyceride, Schizandra Sphenanthera Fruit Extract (Magnolia Berry Extract), Theobroma Cacao Extract (Cocoa Extract), Tocopherol (Vitamin E), Water (Aqua), Beta-Sitosterol, Squalene, Glycolipids, Glycosphingolipids, Chamomilla Recutita Flower Extract* (Chamomile Extract Co2).",True
391,PURITO Oat-in Silky Toner 200ml,PURITO,"Avena Sativa (Oat) Seed Water, Butylene Glycol, Glycerin, 1,2-Hexanediol (Solvent), Limnanthes Alba (Meadowfoam) Seed Oil, Water, Polyglyceryl-10 Stearate (Surfactants-Emulsifying Agents), Avena Sativa (Oat) Kernel Extract, Ethylhexylglycerin, Beta-Glucan.",True
392,Alpha-H Generation Glow Daily Resurfacing Essence with 5% AHA Complex 100ml,Alpha-H,"Aqua (Water), Butylene Glycol, Dodecane, Vaccinium Myrtillus Fruit Extract, Acrylamide/Sodium Acryloyldimethyltaurate Copolymer, Saccharum Officinarum (Sugarcane) Extract, Phenoxyethanol, Polysorbate 80, Isohexadecane, Hydroxyethylcellulose, Tocopherol Acetate, Caprylyl Glycol, Eucalyptus Globulus Leaf Extract, Carbomer, Citrus Aurantium Dulcis (Orange) Fruit Extract, Citrus Limon (Lemon) Fruit Extract, Coco-Caprylate/Caprate, Lactic Acid, Melaleuca Alternifolia (Tea Tree) Leaf Extract, Acer Saccharium (Sugar Maple) Extract, Chamomilla Recutita (Matricaria) Flower Extract, Sorbitan Oleate, Hydroxyacetophenone, Sodium Benzoate, 1,2-Hexanediol, Anthemis Nobilis Flower Extract, Camellia Sinensis Leaf Extract, Citric Acid, Decyl Glucoside, Lauryl Glucoside, Lavandula Angustifolia (Lavender) Flower/Leaf/Stem Extract, Mentha Viridis (Spearmint) Extract, Pogostemon Cablin Leaf Extract, Rose Extract, Lactobacillus Ferment Lysate, Saccharomyces Lysate.",True