# Conventional Skincare Dataset Preparation

## Introduction

In this notebook, we prepare a conventional skincare dataset for comparison with the clean skincare dataset.

Our goal is to:
- load the conventional products dataset
- keep only relevant skincare products
- identify major conventional brands
- select a balanced sample of products
- export the cleaned dataset in the same structure as the clean dataset

In [38]:
import pandas as pd

## Data Collection

We load the conventional products dataset and inspect its structure.
At this stage, we only want to understand the available columns and the overall size of the dataset.

In [39]:
# Load the conventional products dataset
df = pd.read_csv("../data/conventional_products.csv")

In [40]:
df.shape

(1472, 11)

In [41]:
df.head()

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

In [42]:
df.columns.tolist()

['Label',
 'Brand',
 'Name',
 'Price',
 'Rank',
 'Ingredients',
 'Combination',
 'Dry',
 'Normal',
 'Oily',
 'Sensitive']

In [43]:
# Select only the relevant columns for our analysis
df = df[["Brand", "Name", "Ingredients"]]

# Rename columns to match the structure of the clean dataset
df = df.rename(columns={
    "Brand": "Product Brand",
    "Name": "Product Name"
})

In [44]:
df.head()

,Product Brand,Product Name,Ingredients
0,LA MER,Crème de la Mer,"Algae (Seaweed) Extract, Mineral Oil, Petrolat..."
1,SK-II,Facial Treatment Essence,"Galactomyces Ferment Filtrate (Pitera), Butyle..."
2,DRUNK ELEPHANT,Protini™ Polypeptide Cream,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary..."
3,LA MER,The Moisturizing Soft Cream,"Algae (Seaweed) Extract, Cyclopentasiloxane, P..."
4,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,"Water, Snail Secretion Filtrate, Phenyl Trimet..."

In [45]:
# Combine brand and product name into one column
df["Product Name"] = df["Product Brand"] + " " + df["Product Name"]

In [46]:
df.head()

,Product Brand,Product Name,Ingredients
0,LA MER,LA MER Crème de la Mer,"Algae (Seaweed) Extract, Mineral Oil, Petrolat..."
1,SK-II,SK-II Facial Treatment Essence,"Galactomyces Ferment Filtrate (Pitera), Butyle..."
2,DRUNK ELEPHANT,DRUNK ELEPHANT Protini™ Polypeptide Cream,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary..."
3,LA MER,LA MER The Moisturizing Soft Cream,"Algae (Seaweed) Extract, Cyclopentasiloxane, P..."
4,IT COSMETICS,IT COSMETICS Your Skin But Better™ CC+™ Cream ...,"Water, Snail Secretion Filtrate, Phenyl Trimet..."

In [47]:
# Add column to indicate these are conventional products
df["Clean Product"] = False

In [48]:
df.head()

,Product Brand,Product Name,Ingredients,Clean Product
0,LA MER,LA MER Crème de la Mer,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",False
1,SK-II,SK-II Facial Treatment Essence,"Galactomyces Ferment Filtrate (Pitera), Butyle...",False
2,DRUNK ELEPHANT,DRUNK ELEPHANT Protini™ Polypeptide Cream,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",False
3,LA MER,LA MER The Moisturizing Soft Cream,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",False
4,IT COSMETICS,IT COSMETICS Your Skin But Better™ CC+™ Cream ...,"Water, Snail Secretion Filtrate, Phenyl Trimet...",False

In [49]:
df.columns

Index(['Product Brand', 'Product Name', 'Ingredients', 'Clean Product'], dtype='str')

In [50]:
# Reload original dataset to access 'Label' again
df_full = pd.read_csv("../data/conventional_products.csv")

In [51]:
df_full["Label"].value_counts()

Label
Moisturizer    298
Cleanser       281
Face Mask      266
Treatment      248
Eye cream      209
Sun protect    170
Name: count, dtype: int64

In [52]:
skincare_labels = [
    "Moisturizer",
    "Cleanser",
    "Face Mask",
    "Treatment",
    "Eye cream"
]

In [53]:
# Filter dataset to only skincare products
df_filtered = df_full[df_full["Label"].isin(skincare_labels)]

In [54]:
df_filtered["Label"].value_counts()

Label
Moisturizer    298
Cleanser       281
Face Mask      266
Treatment      248
Eye cream      209
Name: count, dtype: int64

In [55]:
df_filtered.shape

(1302, 11)

In [56]:
# Count how many products each brand has
brand_counts = df_filtered["Brand"].value_counts()

brand_counts.head(20)

Brand
SEPHORA COLLECTION    65
CLINIQUE              63
ORIGINS               53
SHISEIDO              51
MURAD                 43
FRESH                 42
PETER THOMAS ROTH     42
KIEHL'S SINCE 1851    41
DR. JART+             41
KATE SOMERVILLE       32
CAUDALIE              30
LANCÔME               30
LA MER                29
PERRICONE MD          29
OLEHENRIKSEN          27
ESTÉE LAUDER          27
FIRST AID BEAUTY      26
PHILOSOPHY            26
ALGENIST              26
DIOR                  25
Name: count, dtype: int64

In [57]:
selected_brands = [
    "SEPHORA COLLECTION",
    "CLINIQUE",
    "SHISEIDO",
    "MURAD",
    "PETER THOMAS ROTH",
    "KIEHL'S SINCE 1851",
    "DR. JART+",
    "LANCÔME",
    "LA MER",
    "ESTÉE LAUDER"
]

In [58]:
# Keep only selected brands
df_brands = df_filtered[df_filtered["Brand"].isin(selected_brands)]

In [59]:
df_brands["Brand"].value_counts()
df_brands.shape

(432, 11)

In [60]:
# Take up to 15 products per brand
df_sampled = df_brands.groupby("Brand").head(15)

In [61]:
df_sampled.shape
df_sampled["Brand"].value_counts()

Brand
LA MER                15
KIEHL'S SINCE 1851    15
CLINIQUE              15
SHISEIDO              15
DR. JART+             15
ESTÉE LAUDER          15
PETER THOMAS ROTH     15
LANCÔME               15
MURAD                 15
SEPHORA COLLECTION    15
Name: count, dtype: int64

In [62]:
df_sampled["Product Name"] = df_sampled["Brand"] + " " + df_sampled["Name"]

In [63]:
df_final = df_sampled[["Brand", "Product Name", "Ingredients"]]

In [64]:
df_final["Clean Product"] = False

In [65]:
df_final.columns = ["Product Brand", "Product Name", "Ingredients", "Clean Product"]

In [66]:
df_final.to_csv("conventional_skincare_final.csv", index=False)

In [67]:
df_final.head()

,Product Brand,Product Name,Ingredients,Clean Product
0,LA MER,LA MER Crème de la Mer,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",False
3,LA MER,LA MER The Moisturizing Soft Cream,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",False
8,KIEHL'S SINCE 1851,KIEHL'S SINCE 1851 Ultra Facial Cream,"Water, Glycerin, Cyclohexasiloxane, Squalane, ...",False
9,LA MER,LA MER Little Miss Miracle Limited-Edition Crè...,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",False
11,KIEHL'S SINCE 1851,KIEHL'S SINCE 1851 Midnight Recovery Concentrate,Caprylic/Capric Triglyceride Dicaprylyl Carbon...,False

In [68]:
df_final.shape

(150, 4)

## Data Cleaning

In this section, we perform basic cleaning steps to ensure consistency and usability of the dataset.

This includes:
- handling missing values
- standardizing text fields
- removing duplicates

In [69]:
df_final.isna().sum()

Product Brand    0
Product Name     0
Ingredients      0
Clean Product    0
dtype: int64

In [70]:
(df_final["Ingredients"].str.strip() == "").sum()

np.int64(0)

In [71]:
df_final["Product Name"].duplicated().sum()

np.int64(0)

In [72]:
df_final["Product Name"] = df_final["Product Name"].str.strip()
df_final["Product Brand"] = df_final["Product Brand"].str.strip()
df_final["Ingredients"] = df_final["Ingredients"].str.strip()

In [73]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 150 entries, 0 to 842
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product Brand  150 non-null    str
 1   Product Name   150 non-null    str
 2   Ingredients    150 non-null    str
 3   Clean Product  150 non-null    bool
dtypes: bool(1), str(3)
memory usage: 4.8 KB

In [74]:
df_final.to_csv("../data/conventional_skincare_final.csv", index=False)